import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Lora } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} font-sans antialiased`}
      >
        <div className="max-w-[1200px] mx-auto px-5 lg:px-0 mt-5">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
